### ISSUE TITLE
[Core] Biome colors for textures

### ISSUE THREAD

**Issue by h45h74x** [h45h74x/mc-source#22]
#### Description:
Add an optional string-based "biome" selector (hierarchically between "String" and "Sides") for textures in the `config.yml` configuration file. Depending on the value, a different `.vmt` file (which contains a RGB "color" value to adjust the hue) can be used.

#### Example:
```yml
grass_block:
      texture:
        states:
          default:
            sides:
              side: 
                biome:
                  "minecraft:plains": grass_block_side_plains
                  "minecraft:swamp": grass_block_side_swamp
              top: 
                biome:
                  "minecraft:plains": grass_block_top_plains
                  "minecraft:swamp": grass_block_top_swamp
          snowy:
            sides:
              side: grass_block_side
              top: grass_block_snow
```

#### Tasks:
- [ ] Update documentation in [Configuration.md](https://github.com/h45h74x/mc-source/blob/master/McSource/Configuration.md)
- [ ] Get the corret texture based on biome information in Block datamodels via the config handler
